# Generated by Django 4.2.5 on 2024-05-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='note',
        ),
    ]
