# Generated by Django 4.2.5 on 2024-04-25 09:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_message_time_created_alter_thread_time_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_cwarning'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cWarning',
            new_name='Warnings_history',
        ),
    ]
