# Generated by Django 4.2.5 on 2024-04-25 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_rename_cwarning_warnings_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings_history',
            name='warned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
