# Generated by Django 4.2.5 on 2024-04-25 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_message_time_created_alter_thread_time_created'),
        ('users', '0007_alter_warnings_history_warned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings_history',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.message'),
        ),
    ]
