# Generated by Django 4.2.5 on 2024-04-25 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_warnings_history_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='warnings_history',
            name='time_warned',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 25, 11, 28, 37, 206285), null=True),
        ),
    ]
