# Generated by Django 4.2.5 on 2024-04-25 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_warnings_history_time_warned'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='warnings_history',
            name='time_warned',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 11, 54, 7, 685826)),
        ),
    ]
