# Generated by Django 5.0.1 on 2024-04-29 09:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_warnings_history_time_warned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
        migrations.AlterField(
            model_name='warnings_history',
            name='time_warned',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 11, 39, 6, 25368)),
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_theme', models.SmallIntegerField(default=0)),
                ('account_visibility', models.SmallIntegerField(choices=[(0, 'Everyone can see profile'), (1, 'Only forum members can see profile'), (2, 'Nobody can see profile (beside administrators/moderators)')], default=0)),
                ('private_messages', models.SmallIntegerField(choices=[(0, 'Everyone can send dms'), (1, 'Administrators/moderators only')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
