# Generated by Django 5.0.1 on 2024-04-29 10:18

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_alter_message_time_created_alter_thread_time_created'),
        ('users', '0020_profile_active_notifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.RenameModel(
            old_name='Preferences',
            new_name='Preference',
        ),
        migrations.AlterField(
            model_name='warnings_history',
            name='time_warned',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 12, 18, 37, 302715)),
        ),
    ]
