# Generated by Django 5.0.1 on 2024-04-30 08:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_warnings_history_time_warned'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 10, 38, 56, 213147)),
        ),
        migrations.AddField(
            model_name='notification',
            name='warning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.warnings_history'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.SmallIntegerField(choices=[(0, 'warning'), (2, 'report'), (3, 'message_delete'), (4, 'message_edit'), (5, 'profile_edit'), (6, 'thread_delete')]),
        ),
        migrations.AlterField(
            model_name='warnings_history',
            name='time_warned',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 10, 38, 56, 212206)),
        ),
    ]
