# Generated by Django 5.0.1 on 2024-04-30 09:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0014_alter_report_time_created'),
        ('users', '0024_notification_time_created_notification_warning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_report', to='moderation.report'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 11, 4, 17, 61653)),
        ),
        migrations.AlterField(
            model_name='warnings_history',
            name='time_warned',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 11, 4, 17, 61653)),
        ),
    ]
