# Generated by Django 4.2.5 on 2024-05-07 07:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_messages', '0005_alter_private_message_time_created'),
        ('users', '0039_alter_notification_time_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warnings_history',
            old_name='content',
            new_name='forum_msg',
        ),
        migrations.AddField(
            model_name='warnings_history',
            name='profile_msg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profile_messages.private_message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 9, 34, 9, 143783)),
        ),
        migrations.AlterField(
            model_name='warnings_history',
            name='time_warned',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 9, 34, 9, 142782)),
        ),
    ]
