# Generated by Django 4.2.5 on 2024-05-13 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_notification_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.SmallIntegerField(choices=[(0, 'warning'), (2, 'report'), (3, 'message_delete'), (4, 'message_edit'), (5, 'profile_edit'), (6, 'thread_delete'), (7, 'thread_change')]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 9, 18, 39, 702591)),
        ),
        migrations.AlterField(
            model_name='warnings_history',
            name='time_warned',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 9, 18, 39, 702591)),
        ),
    ]
