# Generated by Django 5.0.1 on 2024-05-13 17:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_messages', '0015_alter_private_message_time_created'),
        ('users', '0049_alter_notification_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 19, 42, 3, 508981)),
        ),
        migrations.AlterField(
            model_name='warnings_history',
            name='profile_msg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_messages.private_message'),
        ),
        migrations.AlterField(
            model_name='warnings_history',
            name='time_warned',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 19, 42, 3, 507653)),
        ),
    ]
