# Generated by Django 4.2.5 on 2024-04-24 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_message_time_created_alter_thread_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='msg_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 14, 48, 4, 208721)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 14, 48, 4, 208721)),
        ),
    ]
