# Generated by Django 5.0.1 on 2024-04-29 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_alter_message_time_created_alter_thread_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='type_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 18, 37, 53, 117446)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 18, 37, 53, 117446)),
        ),
    ]
