# Generated by Django 5.0.1 on 2024-04-29 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_node_type_private_alter_message_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='staff_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 18, 41, 51, 599315)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 18, 41, 51, 599315)),
        ),
    ]
