# Generated by Django 5.0.1 on 2024-04-30 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0027_alter_message_time_created_alter_thread_msg_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 11, 4, 17, 56689)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 11, 4, 17, 56689)),
        ),
    ]
