# Generated by Django 5.0.1 on 2024-04-30 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0028_alter_message_time_created_alter_thread_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='invis_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='invis_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 11, 42, 28, 777961)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 11, 42, 28, 776970)),
        ),
    ]
