# Generated by Django 5.0.1 on 2024-05-06 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0033_thread_deleted_by_alter_message_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 18, 53, 3, 901076)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 18, 53, 3, 900087)),
        ),
    ]
