# Generated by Django 4.2.5 on 2024-05-07 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0048_alter_message_time_created_alter_thread_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 12, 0, 3, 968126)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 12, 0, 3, 968126)),
        ),
    ]
