# Generated by Django 5.0.1 on 2024-05-07 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0049_node_slug_thread_slug_alter_message_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='user_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 19, 38, 45, 532933)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 19, 38, 45, 532933)),
        ),
    ]
