# Generated by Django 4.2.5 on 2024-05-13 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0050_node_user_only_alter_message_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 9, 18, 39, 698591)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 9, 18, 39, 698591)),
        ),
    ]
