# Generated by Django 4.2.5 on 2024-05-13 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0051_message_is_start_alter_message_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='time_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 9, 53, 23, 640578)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 9, 53, 23, 640578)),
        ),
    ]
