# Generated by Django 5.0.1 on 2024-05-06 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='private_message',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 20, 35, 34, 169775)),
        ),
    ]
