# Generated by Django 4.2.5 on 2024-05-07 06:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_messages', '0003_alter_private_message_time_created_dialog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private_message',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_messages.dialog'),
        ),
        migrations.AlterField(
            model_name='private_message',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 8, 54, 46, 145994)),
        ),
    ]
