# Generated by Django 5.0.1 on 2024-05-13 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_messages', '0014_alter_private_message_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private_message',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 19, 42, 3, 507653)),
        ),
    ]
