# Generated by Django 5.0.6 on 2024-05-23 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_messages', '0017_alter_private_message_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private_message',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 13, 22, 11, 805375)),
        ),
    ]
