# Generated by Django 5.0.1 on 2024-04-26 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='is_declined',
            new_name='is_rejected',
        ),
        migrations.AlterField(
            model_name='report',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 21, 19, 42, 698645)),
        ),
    ]
