# Generated by Django 5.0.1 on 2024-04-26 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_rename_is_declined_report_is_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 21, 30, 37, 340091)),
        ),
    ]
