# Generated by Django 5.0.1 on 2024-04-26 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_alter_report_time_changed_alter_report_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 21, 32, 41, 464448)),
        ),
    ]
