# Generated by Django 5.0.1 on 2024-04-25 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_report_closed_by_report_time_changed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time_changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 21, 20, 49, 512848)),
        ),
    ]
