# Generated by Django 4.2.5 on 2024-04-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0009_alter_report_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
